changelog_type: pull_request
header_prefix: 'Version:'
commit_changelog: true
comment_changelog: false
include_unlabeled_changes: true
unlabeled_group_title: 'Other Changes'
pull_request_title_regex: '^Release'
version_regex: 'v?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})'
